name: Playwright Tests

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs daily at midnight (adjust if necessary)

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Use the latest stable version
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        
    - name: Install dependencies
      run: npm ci  # Ensures a clean install of dependencies
      
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps  # Installs necessary browsers and deps

    - name: Run Playwright tests
      run: npx playwright test  # Runs your Playwright test suite

    - uses: actions/upload-artifact@v4  # Upload test reports as artifacts
      if: always()  # Ensures report is uploaded even if tests fail
      with:
        name: playwright-report  # Artifact name
        path: playwright-report/  # Path where the report is stored
        retention-days: 30  # Keep the artifact for 30 days
